### ISSUE TITLE
DAPs errors on the guide

### ISSUE THREAD

**Issue by aknguyen7** [OpenLiberty/iguide-microprofile-config-intro#254]
1. Frame: 1 - 12

![image](https://user-images.githubusercontent.com/30509453/77695558-f88df400-6f79-11ea-909e-f17c834a19b9.png)

2. DAP errors on the view that is 1439px wide or less

![image](https://user-images.githubusercontent.com/30509453/77695647-19564980-6f7a-11ea-87cb-34f8bbb244c6.png)

a. The table in the playground
![image](https://user-images.githubusercontent.com/30509453/77695245-769dcb00-6f79-11ea-8425-e8ffc16941b2.png)

b. Background contrast on pod with error:

![image](https://user-images.githubusercontent.com/30509453/77696094-d5177900-6f7a-11ea-87d1-fd9be27f6916.png)

c. editor button frame

![image](https://user-images.githubusercontent.com/30509453/77697002-05134c00-6f7c-11ea-88b0-f57bc383c494.png)

3. Add <title> to the html templates
For example, 
<img width="633" alt="image" src="https://user-images.githubusercontent.com/29490139/77962240-e0331780-72a0-11ea-9782-b11643839221.png">

**Comment by steven1046** [comment]
We'll have to use the new IBM accessibility tool https://www.ibm.com/able/toolkit/ instead of DAP.

**Comment by dmorgant** [comment]
Using the IBM Accessibility Checker, we get most of the same errors as we have shown above that were found using DAP.

The sample browser on the right get the following 4 errors:
<img width="533" alt="image" src="https://user-images.githubusercontent.com/29490139/107703805-31b27e00-6c8a-11eb-91da-57d1cee28606.png">

-----------------------

For the table in the playground  we have 3 errors:
<img width="617" alt="image" src="https://user-images.githubusercontent.com/29490139/107819278-e316e980-6d46-11eb-9e49-5300227d1d38.png">
<img width="355" alt="image" src="https://user-images.githubusercontent.com/29490139/107819338-00e44e80-6d47-11eb-999f-456a53e7ae2b.png">

-------------------------

For the pod containing an error message:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/29490139/107819871-db0b7980-6d47-11eb-8699-5bb2f0fc2e9a.png">
<img width="461" alt="image" src="https://user-images.githubusercontent.com/29490139/107819965-03937380-6d48-11eb-9af7-d09ad3ed6959.png">

--------------------------

In single column view,  the TOC gets an error:
<img width="829" alt="image" src="https://user-images.githubusercontent.com/29490139/107820574-02167b00-6d49-11eb-875c-92b4e2d1e5d3.png">
<img width="464" alt="image" src="https://user-images.githubusercontent.com/29490139/107820521-f2973200-6d48-11eb-8151-e64cfc1e4c08.png">

---------------------------

For the editor button frame:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/29490139/107823047-18bed100-6d4d-11eb-804f-4b6bce0c0252.png">
<img width="457" alt="image" src="https://user-images.githubusercontent.com/29490139/107823076-24aa9300-6d4d-11eb-86e4-726bc348208c.png">

**Comment by dmorgant** [comment]
Also reference https://github.com/OpenLiberty/openliberty.io/pull/2037
