### ISSUE TITLE
Align with MP Config 2.0

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/iguide-microprofile-config-intro#262]
Use MP Config 2.0

**Comment by dmorgant** [comment]
https://projects.eclipse.org/projects/technology.microprofile/releases/config-2.0

**Comment by dmorgant** [comment]
The current sample is using MP Config 2.0:

        <dependency>
            <groupId>org.eclipse.microprofile.config</groupId>
            <artifactId>microprofile-config-api</artifactId>
            <version>2.0</version>
        </dependency>
